# Generated by Django 4.0.3 on 2023-03-07 03:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='automobileVO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('import_href', models.CharField(max_length=100, null=True, unique=True)),
                ('vin', models.CharField(max_length=17, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Technician',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('tech_id', models.PositiveSmallIntegerField()),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner_name', models.CharField(max_length=200)),
                ('date', models.DateTimeField()),
                ('reason', models.CharField(max_length=200)),
                ('isVIP', models.BooleanField()),
                ('automobile', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='services', to='service_rest.automobilevo')),
                ('technician', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='technician_services', to='service_rest.technician')),
            ],
            options={
                'ordering': ('owner_name', 'date', 'reason', 'isVIP', 'automobile'),
            },
        ),
    ]
