# Generated by Django 4.0.3 on 2023-03-07 07:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service_rest', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='automobileVO',
            new_name='AutoVO',
        ),
        migrations.AlterModelOptions(
            name='service',
            options={'ordering': ('owner_name', 'date', 'reason', 'isVIP', 'auto')},
        ),
        migrations.RenameField(
            model_name='service',
            old_name='automobile',
            new_name='auto',
        ),
    ]
