# Generated by Django 4.0.3 on 2023-03-07 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_rest', '0002_rename_automobilevo_autovo_alter_service_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='service',
            options={'ordering': ('owner_name', 'date', 'reason', 'auto')},
        ),
        migrations.RemoveField(
            model_name='service',
            name='isVIP',
        ),
        migrations.RemoveField(
            model_name='technician',
            name='tech_id',
        ),
        migrations.AlterField(
            model_name='technician',
            name='id',
            field=models.PositiveSmallIntegerField(primary_key=True, serialize=False),
        ),
    ]
