# Generated by Django 4.0.3 on 2023-03-07 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_rest', '0003_alter_service_options_remove_service_isvip_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='service',
            options={'ordering': ('owner_name', 'date', 'reason', 'isVIP', 'auto')},
        ),
        migrations.AddField(
            model_name='service',
            name='isVIP',
            field=models.BooleanField(default=False),
        ),
    ]
