# Generated by Django 4.0.3 on 2023-03-08 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_rest', '0005_alter_service_isvip'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='isVIP',
            field=models.BooleanField(default=False),
        ),
    ]
