# Generated by Django 4.0.3 on 2023-03-09 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_rest', '0006_alter_service_isvip'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='finish',
            field=models.BooleanField(default=False),
        ),
    ]
